my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: ${{ secrets.GCP_PROJECT_ID }}
      dataset:  ${{ secrets.DBT_DATASET_NAME }}
      threads: 1
      keyfile: ${{ secrets.BIGQUERY_KEY }}
